unicef-polymer/etools-form-builder

package-lock.json, package.json, src/lib/styles/page-layout-styles.ts
[ch19294] Form details style- Reduce padding when in mobile view
=> [ch19294] Form details style- Reduce padding when in mobile view

package-lock.json, package.json
[ch19777]Use new versions of etools-ajax, etools-upload
=> [ch19777]Use new versions of etools-ajax, etools-upload

src/form-attachments-popup/form-attachments-popup.ts
[ch24706] Cannot delete attachments
=> [ch24706] Cannot delete attachments

package.json, src/form-attachments-popup/form-attachments-popup.ts, src/form-fields/base-field.ts, src/form-groups/form-abstract-group.ts, src/form-groups/form-collapsed-card.ts
[ch24713] UI not always updated after upload of attachments
=> [ch24713] UI not always updated after upload of attachments

package-lock.json, package.json
Update upload version, [ch17771] etools-ajax / Show upload progress
=> Update upload version, [ch17771] etools-ajax / Show upload progress

package-lock.json, package.json, src/form-attachments-popup/form-attachments-popup.tpl.ts, src/form-attachments-popup/form-attachments-popup.ts
=> [ch24716]Send composedPath info to etools-upload

package-lock.json, package.json, src/form-attachments-popup/form-attachments-popup.ts
=> [ch26441]Wait for delete

package-lock.json, package.json, src/lib/styles/input-styles.ts
[ch26004] Fix readonly style for text input
=> [ch26004] Fix readonly style for text input

package-lock.json, package.json, src/form-groups/form-collapsed-card.ts
=> [ch27921]Fix can not read properties of undefined

package-lock.json, package.json, src/lib/additional-components/etools-fb-card.ts
=> [ch26783] Change tabs order

package-lock.json, package.json
=> Updated dropdown version

package-lock.json, package.json, src/form-groups/form-collapsed-card.ts
[ch31669] Correct the doubled label
=> [ch31669] Correct the doubled label

package-lock.json, package.json
[ch32428] Use LitElement dropdown for filter component, update necessary packages
=> [ch32428] Use LitElement dropdown for filter component, update necessary packages

package-lock.json, package.json, src/form-fields/single-fields/boolean-field.ts
[ch32046] Data Collection: Toggles not disabled in View mode
=> [ch32046] Data Collection: Toggles not disabled in View mode

package-lock.json, package.json, src/form-fields/abstract-field-base.class.ts, src/form-fields/field-renderer-component.ts
[ch32105] Export questionnaire
=> [ch32105] Export questionnaire

package-lock.json, package.json, src/form-groups/form-abstract-group.ts, src/form-groups/form-collapsed-card.ts
[ch33890] Collapse all entities in data collection by default, if there are more than 2 entities.
=> [ch33890] Collapse all entities in data collection by default, if there are more than 2 entities.

package-lock.json, package.json, src/form-attachments-popup/form-attachments-popup.tpl.ts
[ch35759] FM Shoelace Migration Issues 2
=> [ch35759] FM Shoelace Migration Issues 2

package-lock.json, package.json
Update package, published rc.11
=> Update package, published rc.11

package-lock.json, package.json, src/form-attachments-popup/form-attachments-popup.ts, src/form-fields/abstract-field-base.class.ts, src/form-fields/repeatable-fields/repeatable-attachment-field.ts, src/form-fields/single-fields/number-field.ts, src/form-groups/form-abstract-group.ts, src/lib/additional-components/confirmation-dialog.ts, src/lib/additional-components/etools-fb-card.ts
=> Fix translations

package-lock.json, package.json, src/form-groups/form-card.ts, src/lib/styles/form-builder-card.styles.ts
RC.19, [ch36326] FM Shoelace Migration Issues 5
=> RC.19, [ch36326] FM Shoelace Migration Issues 5

package-lock.json, package.json, src/assets/translations.ts, src/form-fields/field-renderer-component.ts, src/form-fields/single-fields/text-field.ts, src/form-groups/form-abstract-group.ts
[ch36598] Mandatory questions and fields
=> [ch36598] Mandatory questions and fields
